Config = {}

Config.Key = 47 -- U düyməsi

Config.Animations = {
    { label = 'Otur', type = 'scenario', scenario = 'WORLD_HUMAN_SEAT_LEDGE' },
    { label = 'Otur (yerdə)', type = 'scenario', scenario = 'WORLD_HUMAN_PICNIC' },
    { label = 'Yerə uzan', type = 'scenario', scenario = 'WORLD_HUMAN_SUNBATHE' },
    { label = 'Siqaret çək', type = 'scenario', scenario = 'WORLD_HUMAN_SMOKING' },
    { label = 'Qəhvə iç', type = 'scenario', scenario = 'WORLD_HUMAN_DRINKING' },
    { label = 'Telefonda danış', type = 'scenario', scenario = 'WORLD_HUMAN_MOBILE_PHONE' },
    { label = 'Kompüterlə işlə', type = 'scenario', scenario = 'WORLD_HUMAN_STAND_MOBILE' },
    { label = 'Ayaq üstə gözlə', type = 'scenario', scenario = 'WORLD_HUMAN_AA_SMOKE' },
    { label = 'Yaz', type = 'scenario', scenario = 'WORLD_HUMAN_CLIPBOARD' },
    { label = 'Bax', type = 'scenario', scenario = 'WORLD_HUMAN_BINOCULARS' },
    { label = 'Salavat', type = 'scenario', scenario = 'WORLD_HUMAN_GUARD_STAND' },
    { label = 'Salam ver', dict = 'gestures@m@standing@casual', anim = 'gesture_hello' },
    { label = 'Əl yellə', dict = 'gestures@m@standing@casual', anim = 'gesture_wave' },
    { label = 'Ayağa qalx', dict = 'gestures@m@standing@casual', anim = 'gesture_cheer' },
    { label = 'Əlləri aç', dict = 'gestures@m@standing@casual', anim = 'gesture_howdy' },
    { label = 'Başını tərpət', dict = 'gestures@m@standing@casual', anim = 'gesture_nod_yes' },
    { label = 'Başını yoxla', dict = 'gestures@m@standing@casual', anim = 'gesture_nod_no' },
    { label = 'Rəqs et (klassik)', dict = 'anim@amb@nightclub@lazlow@hi_peds@', anim = 'low_center_dance_male_female' },
    { label = 'Rəqs et (klub)', dict = 'anim@amb@nightclub@lazlow@hi_peds@', anim = 'low_down_dance_male_female' },
    { label = 'Qazanc', dict = 'anim@amb@casino@valet@', anim = 'idle_a' },
    { label = 'İdman (təkan)', dict = 'amb@world_human_push_ups@male@base', anim = 'base' },
    { label = 'İdman (çömbəlmə)', dict = 'amb@world_human_squat@male@base', anim = 'base' },
    { label = 'Ağrı', dict = 'misscommon@respond', anim = 'pain_reaction' },
    { label = 'Sərxoş', dict = 'random@drunk_driving', anim = 'drunk_driver_lead_away_fail' },
-- ═══════ 196 genişlənmə (50+) ═══════
    { label = 'Qəhvə', type = 'scenario', scenario = 'WORLD_HUMAN_AA_COFFEE' },
    { label = 'Torpaq ək', type = 'scenario', scenario = 'WORLD_HUMAN_GARDEN_PLANT' },
    { label = 'Yarpaq süpür', type = 'scenario', scenario = 'WORLD_HUMAN_GARDEN_LEAF_RAKE' },
    { label = 'Qaynaqçı', type = 'scenario', scenario = 'WORLD_HUMAN_WELDING' },
    { label = 'Təmizlikçi', type = 'scenario', scenario = 'WORLD_HUMAN_JANITOR' },
    { label = 'İdman (yerdə)', type = 'scenario', scenario = 'WORLD_HUMAN_SIT_UPS' },
    { label = 'Kamera', type = 'scenario', scenario = 'WORLD_HUMAN_STAND_CAMERA' },
    { label = 'Məktub', type = 'scenario', scenario = 'WORLD_HUMAN_PAPER_NOTE' },
    { label = 'Barmaqla işarə', type = 'scenario', scenario = 'WORLD_HUMAN_POINT_AT' },
    { label = 'Yerə bax', type = 'scenario', scenario = 'WORLD_HUMAN_LOOK_GROUND' },
    { label = 'Gözəlləşdir', type = 'scenario', scenario = 'WORLD_HUMAN_PICNIC' },
    { label = 'Salam (5-ci)', type = 'dict', dict = 'mp_player_int_uppersalute', anim = 'playerrsalute' },
    { label = 'Rəqs (dağ)', type = 'dict', dict = 'special_ped@mountain_dancer@monologue_3@monologue_3a', anim = 'monologue_3a' },
    { label = 'Yumaq', type = 'dict', dict = 'amb@world_human_wash_up@male@base', anim = 'base' },
    { label = 'Boks', type = 'dict', dict = 'amb@world_human_boxing@male@idle_a', anim = 'idle_a' },
    { label = 'Xətt kəsmə (küçə)', type = 'dict', dict = 'amb@code_human_cross_road@male@base', anim = 'base' },
    { label = 'Güc göstər', type = 'dict', dict = 'amb@world_human_muscle_flex@male@base', anim = 'base' },
    { label = 'Boş baxış', type = 'dict', dict = 'amb@world_human_hang_out@male@base', anim = 'base' },
    { label = 'Vaxt: telefon', type = 'dict', dict = 'amb@world_human_stand_mobile@male@text@base', anim = 'base' },
    { label = 'Çay iç', type = 'dict', dict = 'amb@world_human_drinking@male@base', anim = 'base' },
    { label = 'Siqaret (2)', type = 'dict', dict = 'amb@world_human_smoking@male@base', anim = 'base' },
    { label = 'Qapı aç', type = 'dict', dict = 'anim@heists@prison_finish', anim = 'unlocked' },
    { label = 'Kartof yığ', type = 'dict', dict = 'amb@world_human_crouch_scan@male@base', anim = 'base' },
    { label = 'Axtarış', type = 'dict', dict = 'amb@world_human_stand_search@male@base', anim = 'base' },
    { label = 'Zəng et', type = 'dict', dict = 'cellphone@in_car@ds@std@call', anim = 'out_of_hold' },
{ label = 'Utan', type = 'dict', dict = 'mp_player_int_uppersalute', anim = 'playerrsalute' },
    { label = 'Gördüm səni', type = 'dict', dict = 'mp_common', anim = 'gest_hello_2' },
    { label = 'Xeyir deyil', type = 'dict', dict = 'mp_player_int_upper_chat', anim = 'mp_player_int_playerrsalute' },
-- ═══════ 196 genişlənmə (150+) ═══════
    { label = 'Ayaq üstə dincəl', type = 'scenario', scenario = 'WORLD_HUMAN_HANG_OUT' },
    { label = 'Divara söykən', type = 'scenario', scenario = 'WORLD_HUMAN_LEANING' },
    { label = 'Otaq təmizlə', type = 'scenario', scenario = 'WORLD_HUMAN_MAID_CLEAN' },
    { label = 'Pillədə otur', type = 'scenario', scenario = 'WORLD_HUMAN_SEAT_STEPS' },
    { label = 'Qəhrəman dayanışı', type = 'scenario', scenario = 'WORLD_HUMAN_STAND_IMPOSING' },
    { label = 'Ağılsız dayanış', type = 'scenario', scenario = 'WORLD_HUMAN_STAND_STUPID' },
    { label = 'Odun yanında dayan', type = 'scenario', scenario = 'WORLD_HUMAN_STAND_FIRE' },
    { label = 'Yoqa', type = 'scenario', scenario = 'WORLD_HUMAN_YOGA' },
    { label = 'Maşın bax (mexanik)', type = 'scenario', scenario = 'WORLD_HUMAN_VEHICLE_MECHANIC' },
    { label = 'Əl yumaq', type = 'scenario', scenario = 'WORLD_HUMAN_WASH_UP' },
    { label = 'Pəncərə bax', type = 'scenario', scenario = 'WORLD_HUMAN_WINDOW_SHOP' },
    { label = 'Çəkic vur', type = 'scenario', scenario = 'WORLD_HUMAN_HAMMERING' },
    { label = 'Güc nümayişi', type = 'scenario', scenario = 'WORLD_HUMAN_MUSCLE_FLEX' },
    { label = 'Təkanla qalx', type = 'scenario', scenario = 'WORLD_HUMAN_PUSH_UPS' },
    { label = 'Yerdə otur (idman)', type = 'scenario', scenario = 'WORLD_HUMAN_SIT_UPS' },
    { label = 'Diz çökmüş iş', type = 'scenario', scenario = 'WORLD_HUMAN_SQUAT' },
    { label = 'Alqışla', type = 'scenario', scenario = 'WORLD_HUMAN_CHEERING' },
    { label = 'Optik bax', type = 'scenario', scenario = 'WORLD_HUMAN_BINOCULARS' },
    { label = 'Kompüter (noutbuk)', type = 'scenario', scenario = 'WORLD_HUMAN_CPR' },
    { label = 'Çubuqla balıq', type = 'scenario', scenario = 'WORLD_HUMAN_STAND_FISHING' },
    { label = 'Kamera çək', type = 'scenario', scenario = 'WORLD_HUMAN_STAND_CAMERA' },
    { label = 'Məktub yaz', type = 'scenario', scenario = 'WORLD_HUMAN_PAPER_NOTE' },
    { label = 'Baxış (yerdə)', type = 'scenario', scenario = 'WORLD_HUMAN_LOOK_GROUND' },
    { label = 'Siqaret (passiv)', type = 'scenario', scenario = 'WORLD_HUMAN_SMOKING_PASSIVE' },
    { label = 'Yanğın qoruyu', type = 'scenario', scenario = 'WORLD_HUMAN_GUARD_STAND' },
    { label = 'İstirahət (günəş)', type = 'scenario', scenario = 'WORLD_HUMAN_SUNBATHE' },
    { label = 'Çimərlik (arxa)', type = 'scenario', scenario = 'WORLD_HUMAN_SUNBATHE_BACK' },
    { label = 'Qapıçı', type = 'scenario', scenario = 'WORLD_HUMAN_DOOR_MAN' },
    { label = 'Süpürgə', type = 'scenario', scenario = 'WORLD_HUMAN_GARDEN_LEAF_RAKE' },
    { label = 'Fidan ək', type = 'scenario', scenario = 'WORLD_HUMAN_GARDEN_PLANT' },
    { label = 'Yemək bişir', type = 'scenario', scenario = 'WORLD_HUMAN_GRILL' },
    { label = 'Piknik', type = 'scenario', scenario = 'WORLD_HUMAN_PICNIC' },
    { label = 'Telefon (yazı)', type = 'scenario', scenario = 'WORLD_HUMAN_STAND_MOBILE' },
    { label = 'Avtomaşın yuyucu', type = 'scenario', scenario = 'WORLD_HUMAN_CAR_WASH' },
    { label = 'Qol oynatma', type = 'scenario', scenario = 'WORLD_HUMAN_SPORT_STRETCH' },
    { label = 'Yelləncək', type = 'scenario', scenario = 'WORLD_HUMAN_SWING' },
    { label = 'Kassir', type = 'scenario', scenario = 'WORLD_HUMAN_REGISTER' },
    { label = 'Piyada işarəsi', type = 'scenario', scenario = 'WORLD_HUMAN_CROSS_ROAD' },
    { label = 'Küçə xəbərdarlığı', type = 'scenario', scenario = 'WORLD_HUMAN_STAND_WHISKEY' },
    { label = 'Qazma', type = 'scenario', scenario = 'WORLD_HUMAN_DIG' },
    { label = 'Salam ver (qadın)', type = 'dict', dict = 'gestures@f@standing@casual', anim = 'gesture_hello' },
    { label = 'Əl yellə (qadın)', type = 'dict', dict = 'gestures@f@standing@casual', anim = 'gesture_wave' },
    { label = 'Alqış (qadın)', type = 'dict', dict = 'gestures@f@standing@casual', anim = 'gesture_cheer' },
    { label = 'Razılıq (qadın)', type = 'dict', dict = 'gestures@f@standing@casual', anim = 'gesture_nod_yes' },
    { label = 'İmtina (qadın)', type = 'dict', dict = 'gestures@f@standing@casual', anim = 'gesture_nod_no' },
    { label = 'Çağır (qadın)', type = 'dict', dict = 'gestures@f@standing@casual', anim = 'gesture_come_here' },
    { label = 'Gəlir məni (qadın)', type = 'dict', dict = 'gestures@f@standing@casual', anim = 'gesture_bring_it' },
    { label = 'Şübhə (qadın)', type = 'dict', dict = 'gestures@f@standing@casual', anim = 'gesture_shrug' },
    { label = 'Barmaqla işarə', type = 'dict', dict = 'gestures@m@standing@casual', anim = 'gesture_point' },
    { label = 'Bəyənirəm', type = 'dict', dict = 'gestures@m@standing@casual', anim = 'gesture_thumbs_up' },
    { label = 'Sülh işarəsi', type = 'dict', dict = 'gestures@m@standing@casual', anim = 'gesture_peace' },
    { label = 'Cavab göstər', type = 'dict', dict = 'gestures@m@standing@casual', anim = 'gesture_come_here' },
    { label = 'Mənə gəl', type = 'dict', dict = 'gestures@m@standing@casual', anim = 'gesture_bring_it' },
    { label = 'Çiyin at', type = 'dict', dict = 'gestures@m@standing@casual', anim = 'gesture_shrug' },
    { label = 'Baş əy', type = 'dict', dict = 'gestures@m@standing@casual', anim = 'gesture_bow' },
    { label = 'Hava gitara', type = 'dict', dict = 'mp_player_int_upper@air_guitar', anim = 'idle_a' },
    { label = 'Hava bas', type = 'dict', dict = 'mp_player_int_upper@air_bass', anim = 'idle_a' },
    { label = 'Rok işarəsi', type = 'dict', dict = 'mp_player_int_upper@rock', anim = 'idle_a' },
    { label = 'Qəzəbli', type = 'dict', dict = 'mp_player_int_upper@angry', anim = 'idle_a' },
    { label = 'Ağlama', type = 'dict', dict = 'mp_player_int_upper@cry', anim = 'idle_a' },
    { label = 'Yellən', type = 'dict', dict = 'mp_player_int_upper@wave', anim = 'idle_a' },
    { label = 'Alqış', type = 'dict', dict = 'mp_player_int_upper@clap', anim = 'idle_a' },
    { label = 'Düşüncəli', type = 'dict', dict = 'mp_player_int_upper@think', anim = 'idle_a' },
    { label = 'Arxası yığcam', type = 'dict', dict = 'mp_player_int_upper@crossarm', anim = 'idle_a' },
    { label = 'Şübhəli baxış', type = 'dict', dict = 'mp_player_int_upper@scratch', anim = 'idle_a' },
    { label = 'Narahat', type = 'dict', dict = 'mp_player_int_upper@impatient', anim = 'idle_a' },
    { label = 'Siqaret (üst)', type = 'dict', dict = 'mp_player_int_upper@smoking', anim = 'idle_a' },
    { label = 'Bəyən (ümumi)', type = 'dict', dict = 'mp_player_int_upper@thumbsup', anim = 'idle_a' },
    { label = 'Utanma', type = 'dict', dict = 'mp_player_int_upper@shy', anim = 'idle_a' },
    { label = 'Səbir', type = 'dict', dict = 'mp_player_int_upper@wait', anim = 'idle_a' },
    { label = 'Zəng çal', type = 'dict', dict = 'mp_player_int_upper@phone', anim = 'idle_a' },
    { label = 'Uçan öpüş', type = 'dict', dict = 'mp_player_int_upper@kiss', anim = 'idle_a' },
    { label = 'Yuxarı baxış', type = 'dict', dict = 'mp_player_int_upper@lookup', anim = 'idle_a' },
    { label = 'Aşağı baxış', type = 'dict', dict = 'mp_player_int_upper@lookdown', anim = 'idle_a' },
    { label = 'Gözlərini yum', type = 'dict', dict = 'mp_player_int_upper@eyesclosed', anim = 'idle_a' },
    { label = 'Gülüş', type = 'dict', dict = 'mp_player_int_upper@laugh', anim = 'idle_a' },
    { label = 'Təəccüb', type = 'dict', dict = 'mp_player_int_upper@surprised', anim = 'idle_a' },
    { label = 'Qorxu', type = 'dict', dict = 'mp_player_int_upper@scared', anim = 'idle_a' },
    { label = 'Sükut', type = 'dict', dict = 'mp_player_int_upper@quiet', anim = 'idle_a' },
    { label = 'Dinlə', type = 'dict', dict = 'mp_player_int_upper@listen', anim = 'idle_a' },
    { label = 'Göstər', type = 'dict', dict = 'mp_player_int_upper@point', anim = 'idle_a' },
    { label = 'Barma düymə', type = 'dict', dict = 'mp_player_int_upper@click', anim = 'idle_a' },
    { label = 'Qələm yaz', type = 'dict', dict = 'mp_player_int_upper@write', anim = 'idle_a' },
    { label = 'Kompüter yaz', type = 'dict', dict = 'mp_player_int_upper@type', anim = 'idle_a' },
    { label = 'Sürücü (mahnı)', type = 'dict', dict = 'mp_player_int_upper@drive', anim = 'idle_a' },
    { label = 'Maşın başqası', type = 'dict', dict = 'mp_player_int_upper@passenger', anim = 'idle_a' },
    { label = 'Özünü göstər', type = 'dict', dict = 'mp_player_int_upper@flex', anim = 'idle_a' },
    { label = 'Gözəllik', type = 'dict', dict = 'mp_player_int_upper@pose', anim = 'idle_a' },
    { label = 'Rəqs (2010)', type = 'dict', dict = 'anim@amb@nightclub@lazlow@hi_peds@', anim = 'low_down_dance_male_female' },
    { label = 'Rəqs (mən)', type = 'dict', dict = 'anim@amb@nightclub@lazlow@hi_peds@', anim = 'low_center_dance_male_female' },
    { label = 'Rəqs (qız)', type = 'dict', dict = 'anim@amb@nightclub@lazlow@hi_peds@', anim = 'med_center_dance_male_female' },
    { label = 'Rəqs (sürətli)', type = 'dict', dict = 'anim@amb@nightclub@lazlow@hi_peds@', anim = 'high_center_dance_male_female' },
    { label = 'Rəqs (mahnı 4)', type = 'dict', dict = 'anim@amb@nightclub@lazlow@hi_peds@', anim = 'low_down_dance_female' },
    { label = 'Gitara çal', type = 'prop', dict = 'amb@world_human_musician@guitar@male@base', anim = 'base', prop = 'prop_guitar_01', bone = 28422 },
    { label = 'Qəhvə iç (kubok)', type = 'prop', dict = 'amb@world_human_drinking@coffee@male@base', anim = 'base', prop = 'prop_cs_coffee_cup', bone = 28422 },
    { label = 'Telefon (əl)', type = 'prop', dict = 'amb@world_human_stand_mobile@male@text@base', anim = 'base', prop = 'prop_phone_ing', bone = 28422 },
    { label = 'Çətir (əl)', type = 'prop', dict = 'anim@amb@casino@valet@', anim = 'idle_a', prop = 'prop_umbrella_01', bone = 28422 },
    { label = 'Boombox (rəqs)', type = 'prop', dict = 'anim@amb@nightclub@lazlow@hi_peds@', anim = 'low_center_dance_male_female', prop = 'prop_boombox_01', bone = 28422 },
    { label = 'Pivə (buxar)', type = 'prop', dict = 'amb@world_human_drinking@beer@male@base', anim = 'base', prop = 'prop_beer_bottle', bone = 28422 },
    { label = 'Pul kisəsi', type = 'prop', dict = 'anim@amb@casino@valet@', anim = 'idle_a', prop = 'prop_money_bag_01', bone = 28422 },
}

Config.CancelAnims = {
    'WORLD_HUMAN_SEAT_LEDGE',
    'WORLD_HUMAN_PICNIC',
    'WORLD_HUMAN_SUNBATHE',
    'WORLD_HUMAN_SMOKING',
    'WORLD_HUMAN_DRINKING',
    'WORLD_HUMAN_MOBILE_PHONE',
    'WORLD_HUMAN_STAND_MOBILE',
    'WORLD_HUMAN_AA_SMOKE',
    'WORLD_HUMAN_CLIPBOARD',
    'WORLD_HUMAN_BINOCULARS',
    'WORLD_HUMAN_GUARD_STAND',
}
