Config = {}

Config.Key = 47 -- U düyməsi

Config.Animations = {
    { label = 'Otur', type = 'scenario', scenario = 'WORLD_HUMAN_SEAT_LEDGE' },
    { label = 'Otur (yerdə)', type = 'scenario', scenario = 'WORLD_HUMAN_PICNIC' },
    { label = 'Yerə uzan', type = 'scenario', scenario = 'WORLD_HUMAN_SUNBATHE' },
    { label = 'Siqaret çək', type = 'scenario', scenario = 'WORLD_HUMAN_SMOKING' },
    { label = 'Qəhvə iç', type = 'scenario', scenario = 'WORLD_HUMAN_DRINKING' },
    { label = 'Telefonda danış', type = 'scenario', scenario = 'WORLD_HUMAN_MOBILE_PHONE' },
    { label = 'Kompüterlə işlə', type = 'scenario', scenario = 'WORLD_HUMAN_STAND_MOBILE' },
    { label = 'Ayaq üstə gözlə', type = 'scenario', scenario = 'WORLD_HUMAN_AA_SMOKE' },
    { label = 'Yaz', type = 'scenario', scenario = 'WORLD_HUMAN_CLIPBOARD' },
    { label = 'Bax', type = 'scenario', scenario = 'WORLD_HUMAN_BINOCULARS' },
    { label = 'Salavat', type = 'scenario', scenario = 'WORLD_HUMAN_GUARD_STAND' },
    { label = 'Salam ver', dict = 'gestures@m@standing@casual', anim = 'gesture_hello' },
    { label = 'Əl yellə', dict = 'gestures@m@standing@casual', anim = 'gesture_wave' },
    { label = 'Ayağa qalx', dict = 'gestures@m@standing@casual', anim = 'gesture_cheer' },
    { label = 'Əlləri aç', dict = 'gestures@m@standing@casual', anim = 'gesture_howdy' },
    { label = 'Başını tərpət', dict = 'gestures@m@standing@casual', anim = 'gesture_nod_yes' },
    { label = 'Başını yoxla', dict = 'gestures@m@standing@casual', anim = 'gesture_nod_no' },
    { label = 'Rəqs et (klassik)', dict = 'anim@amb@nightclub@lazlow@hi_peds@', anim = 'low_center_dance_male_female' },
    { label = 'Rəqs et (klub)', dict = 'anim@amb@nightclub@lazlow@hi_peds@', anim = 'low_down_dance_male_female' },
    { label = 'Qazanc', dict = 'anim@amb@casino@valet@', anim = 'idle_a' },
    { label = 'İdman (təkan)', dict = 'amb@world_human_push_ups@male@base', anim = 'base' },
    { label = 'İdman (çömbəlmə)', dict = 'amb@world_human_squat@male@base', anim = 'base' },
    { label = 'Ağrı', dict = 'misscommon@respond', anim = 'pain_reaction' },
    { label = 'Sərxoş', dict = 'random@drunk_driving', anim = 'drunk_driver_lead_away_fail' },
-- ═══════ 196 genişlənmə (50+) ═══════
    { label = 'Qəhvə', type = 'scenario', scenario = 'WORLD_HUMAN_AA_COFFEE' },
    { label = 'Torpaq ək', type = 'scenario', scenario = 'WORLD_HUMAN_GARDEN_PLANT' },
    { label = 'Yarpaq süpür', type = 'scenario', scenario = 'WORLD_HUMAN_GARDEN_LEAF_RAKE' },
    { label = 'Qaynaqçı', type = 'scenario', scenario = 'WORLD_HUMAN_WELDING' },
    { label = 'Təmizlikçi', type = 'scenario', scenario = 'WORLD_HUMAN_JANITOR' },
    { label = 'İdman (yerdə)', type = 'scenario', scenario = 'WORLD_HUMAN_SIT_UPS' },
    { label = 'Kamera', type = 'scenario', scenario = 'WORLD_HUMAN_STAND_CAMERA' },
    { label = 'Məktub', type = 'scenario', scenario = 'WORLD_HUMAN_PAPER_NOTE' },
    { label = 'Barmaqla işarə', type = 'scenario', scenario = 'WORLD_HUMAN_POINT_AT' },
    { label = 'Yerə bax', type = 'scenario', scenario = 'WORLD_HUMAN_LOOK_GROUND' },
    { label = 'Gözəlləşdir', type = 'scenario', scenario = 'WORLD_HUMAN_PICNIC' },
    { label = 'Salam (5-ci)', type = 'dict', dict = 'mp_player_int_uppersalute', anim = 'playerrsalute' },
    { label = 'Rəqs (dağ)', type = 'dict', dict = 'special_ped@mountain_dancer@monologue_3@monologue_3a', anim = 'monologue_3a' },
    { label = 'Yumaq', type = 'dict', dict = 'amb@world_human_wash_up@male@base', anim = 'base' },
    { label = 'Boks', type = 'dict', dict = 'amb@world_human_boxing@male@idle_a', anim = 'idle_a' },
    { label = 'Xətt kəsmə (küçə)', type = 'dict', dict = 'amb@code_human_cross_road@male@base', anim = 'base' },
    { label = 'Güc göstər', type = 'dict', dict = 'amb@world_human_muscle_flex@male@base', anim = 'base' },
    { label = 'Boş baxış', type = 'dict', dict = 'amb@world_human_hang_out@male@base', anim = 'base' },
    { label = 'Vaxt: telefon', type = 'dict', dict = 'amb@world_human_stand_mobile@male@text@base', anim = 'base' },
    { label = 'Çay iç', type = 'dict', dict = 'amb@world_human_drinking@male@base', anim = 'base' },
    { label = 'Siqaret (2)', type = 'dict', dict = 'amb@world_human_smoking@male@base', anim = 'base' },
    { label = 'Qapı aç', type = 'dict', dict = 'anim@heists@prison_finish', anim = 'unlocked' },
    { label = 'Kartof yığ', type = 'dict', dict = 'amb@world_human_crouch_scan@male@base', anim = 'base' },
    { label = 'Axtarış', type = 'dict', dict = 'amb@world_human_stand_search@male@base', anim = 'base' },
    { label = 'Zəng et', type = 'dict', dict = 'cellphone@in_car@ds@std@call', anim = 'out_of_hold' },
{ label = 'Utan', type = 'dict', dict = 'mp_player_int_uppersalute', anim = 'playerrsalute' },
    { label = 'Gördüm səni', type = 'dict', dict = 'mp_common', anim = 'gest_hello_2' },
    { label = 'Xeyir deyil', type = 'dict', dict = 'mp_player_int_upper_chat', anim = 'mp_player_int_playerrsalute' },
}

Config.CancelAnims = {
    'WORLD_HUMAN_SEAT_LEDGE',
    'WORLD_HUMAN_PICNIC',
    'WORLD_HUMAN_SUNBATHE',
    'WORLD_HUMAN_SMOKING',
    'WORLD_HUMAN_DRINKING',
    'WORLD_HUMAN_MOBILE_PHONE',
    'WORLD_HUMAN_STAND_MOBILE',
    'WORLD_HUMAN_AA_SMOKE',
    'WORLD_HUMAN_CLIPBOARD',
    'WORLD_HUMAN_BINOCULARS',
    'WORLD_HUMAN_GUARD_STAND',
}
