QBCore.Shared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBCore.Shared.Jobs = {
	unemployed = { label = 'Mülki şəxs', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sərbəst', payment = 10 } } },
	bus = { label = 'Avtobus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sürücü', payment = 50 } } },
	judge = { label = 'Məhkəmə', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Hakim', payment = 100 } } },
	lawyer = { label = 'Hüquq firması', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Hüquqşünas', payment = 50 } } },
	reporter = { label = 'Reporter', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Jurnalist', payment = 50 } } },
	trucker = { label = 'Yük daşıma', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sürücü', payment = 50 } } },
	tow = { label = 'Yedək xidməti', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sürücü', payment = 50 } } },
	garbage = { label = 'Zibilçilik', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Toplayıcı', payment = 50 } } },
	vineyard = { label = 'Üzümçülük', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Yığıcı', payment = 50 } } },
	hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Satıcı', payment = 50 } } },

	police = {
		label = 'Hüquq Mühafizəsi',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Təcrübəçi', payment = 50 },
			['1'] = { name = 'Polis əməkdaşı', payment = 75 },
			['2'] = { name = 'Serjant', payment = 100 },
			['3'] = { name = 'Leytenant', payment = 125 },
			['4'] = { name = 'Rəis', isboss = true, payment = 150 },
		},
	},
	ambulance = {
		label = 'Təcili Tibbi Yardım',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Təcrübəçi', payment = 50 },
			['1'] = { name = 'Feldşer', payment = 75 },
			['2'] = { name = 'Həkim', payment = 100 },
			['3'] = { name = 'Cərrah', payment = 125 },
			['4'] = { name = 'Rəis', isboss = true, payment = 150 },
		},
	},
	realestate = {
		label = 'Daşınmaz Əmlak',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Təcrübəçi', payment = 50 },
			['1'] = { name = 'Ev satışı', payment = 75 },
			['2'] = { name = 'Biznes satışı', payment = 100 },
			['3'] = { name = 'Broker', payment = 125 },
			['4'] = { name = 'Menecer', isboss = true, payment = 150 },
		},
	},
	taxi = {
		label = 'Taksi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Təcrübəçi', payment = 50 },
			['1'] = { name = 'Sürücü', payment = 75 },
			['2'] = { name = 'Tədbir sürücüsü', payment = 100 },
			['3'] = { name = 'Satış', payment = 125 },
			['4'] = { name = 'Menecer', isboss = true, payment = 150 },
		},
	},
	cardealer = {
		label = 'Avtosalon',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Təcrübəçi', payment = 50 },
			['1'] = { name = 'Salon satışı', payment = 75 },
			['2'] = { name = 'Biznes satışı', payment = 100 },
			['3'] = { name = 'Maliyyəçi', payment = 125 },
			['4'] = { name = 'Menecer', isboss = true, payment = 150 },
		},
	},
	mechanic = {
		label = '196 Tuninq',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Təcrübəçi', payment = 50 },
			['1'] = { name = 'Yeni başlayan', payment = 75 },
			['2'] = { name = 'Təcrübəli', payment = 100 },
			['3'] = { name = 'İrəli səviyyə', payment = 125 },
			['4'] = { name = 'Menecer', isboss = true, payment = 150 },
		},
	},
	mechanic2 = {
		label = '196 Tuninq — Liman',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Təcrübəçi', payment = 50 },
			['1'] = { name = 'Yeni başlayan', payment = 75 },
			['2'] = { name = 'Təcrübəli', payment = 100 },
			['3'] = { name = 'İrəli səviyyə', payment = 125 },
			['4'] = { name = 'Menecer', isboss = true, payment = 150 },
		},
	},
	mechanic3 = {
		label = '196 Tuninq — Şimal',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Təcrübəçi', payment = 50 },
			['1'] = { name = 'Yeni başlayan', payment = 75 },
			['2'] = { name = 'Təcrübəli', payment = 100 },
			['3'] = { name = 'İrəli səviyyə', payment = 125 },
			['4'] = { name = 'Menecer', isboss = true, payment = 150 },
		},
	},
	beeker = {
		label = 'Beeker Qarajı',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Təcrübəçi', payment = 50 },
			['1'] = { name = 'Yeni başlayan', payment = 75 },
			['2'] = { name = 'Təcrübəli', payment = 100 },
			['3'] = { name = 'İrəli səviyyə', payment = 125 },
			['4'] = { name = 'Menecer', isboss = true, payment = 150 },
		},
	},
	bennys = {
		label = 'Benny Motor İşləri',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Təcrübəçi', payment = 50 },
			['1'] = { name = 'Yeni başlayan', payment = 75 },
			['2'] = { name = 'Təcrübəli', payment = 100 },
			['3'] = { name = 'İrəli səviyyə', payment = 125 },
			['4'] = { name = 'Menecer', isboss = true, payment = 150 },
		},
	},
}
